version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres-image
    build:
      context: ./db
    ports:
      - "5432:5432"

  express:
    container_name: express-container
    image: express-image
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres

